# Generated by Django 3.1.2 on 2020-11-01 07:47

from django.db import migrations, models
import django.db.models.deletion
import storage_backends


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('siteuser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
                ('category_slug', models.SlugField(blank=True)),
                ('category_image', models.ImageField(storage=storage_backends.CategoryMediaStorage(), upload_to='')),
                ('category_line', models.CharField(blank=True, max_length=120, null=True)),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=100)),
                ('role_slug', models.SlugField(blank=True)),
            ],
            options={
                'db_table': 'role',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=100)),
                ('tag_slug', models.SlugField(blank=True)),
            ],
            options={
                'db_table': 'tag',
            },
        ),
        migrations.CreateModel(
            name='BlogRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_on', models.DateTimeField(auto_now_add=True)),
                ('requested_again_on', models.DateTimeField(auto_now=True)),
                ('blog_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.category')),
                ('siteuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siteuser.siteuser')),
            ],
            options={
                'db_table': 'blog_request',
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(help_text='Keep titles short.', max_length=100)),
                ('blog_subtitle', models.CharField(help_text='Short line for subtitle.', max_length=150)),
                ('blog_slug', models.SlugField(blank=True, help_text='Slug will be automatically generated.', max_length=500)),
                ('banner_image', models.ImageField(storage=storage_backends.MediaStorage(), upload_to='')),
                ('banner_image_source', models.CharField(default='', max_length=50)),
                ('content', models.TextField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('moderator_accepted', models.BooleanField(default=False)),
                ('draft', models.BooleanField(default=False)),
                ('preview', models.BooleanField(default=False)),
                ('submitted_for_moderation', models.BooleanField(default=False)),
                ('published', models.BooleanField(default=False)),
                ('blog_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siteuser.siteuser')),
                ('blog_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.category')),
                ('blog_tags', models.ManyToManyField(to='blog.Tag')),
            ],
            options={
                'db_table': 'blog_post',
            },
        ),
    ]
