# Generated by Django 3.0.8 on 2020-08-18 03:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('siteuser', '0001_initial'),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='blog_author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='siteuser.SiteUser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blogrequest',
            name='siteuser',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='siteuser.SiteUser'),
            preserve_default=False,
        ),
    ]
