# Generated by Django 3.0.8 on 2020-08-19 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200818_0903'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_line',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
