# Generated by Django 3.1.2 on 2020-11-01 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20201101_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='banner_image',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_image',
            field=models.ImageField(upload_to=''),
        ),
    ]
