# Generated by Django 3.1.2 on 2020-11-14 07:33

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('blog', '0002_remove_blogpost_blog_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='blog_tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
