# Generated by Django 3.1.2 on 2020-11-14 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogpost_blog_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='blog_tags',
        ),
    ]
