# Generated by Django 3.1.2 on 2020-11-01 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20201101_1631'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='role_name',
        ),
    ]
