# Generated by Django 3.1.2 on 2020-11-01 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_role_role_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='role_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
