# Generated by Django 3.0.8 on 2020-08-29 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200820_0031'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='banner_image_source',
            field=models.CharField(default='', max_length=50),
        ),
    ]
