# Generated by Django 3.1.2 on 2020-11-01 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_role_role_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='blog_tags',
            field=models.ManyToManyField(blank=True, null=True, to='blog.Tag'),
        ),
    ]
