# Generated by Django 3.1.2 on 2020-12-23 01:31

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('blog', '0005_blogtags'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyCustomTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='slug')),
            ],
            options={
                'verbose_name': 'Custom Tag',
                'verbose_name_plural': 'Custom Tags',
            },
        ),
        migrations.AlterModelOptions(
            name='blogtags',
            options={},
        ),
        migrations.RemoveField(
            model_name='blogtags',
            name='name',
        ),
        migrations.RemoveField(
            model_name='blogtags',
            name='slug',
        ),
        migrations.AddField(
            model_name='blogtags',
            name='content_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='blog_blogtags_tagged_items', to='contenttypes.contenttype', verbose_name='content type'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blogtags',
            name='object_id',
            field=models.IntegerField(db_index=True, default=1, verbose_name='object ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blogtags',
            name='tag',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='blog_blogtags_items', to='blog.mycustomtag'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='blog_tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='blog.BlogTags', to='blog.MyCustomTag', verbose_name='Tags'),
        ),
    ]
