# Generated by Django 3.1.2 on 2020-11-15 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20201115_1329'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogrequest',
            old_name='User',
            new_name='user',
        ),
    ]
