# Generated by Django 3.0.8 on 2020-09-05 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200904_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='moderator_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
