# Generated by Django 3.0.8 on 2020-09-27 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20200920_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='blog_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Category'),
        ),
    ]
