# Generated by Django 3.0.8 on 2020-10-01 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20200927_2347'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='submitted_for_moderation',
            field=models.BooleanField(default=False),
        ),
    ]
