# Generated by Django 3.0.8 on 2020-10-02 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_blogpost_submitted_for_moderation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='blog_slug',
            field=models.SlugField(blank=True, help_text='Slug will be automatically generated.', max_length=500),
        ),
    ]
