# Generated by Django 3.1.2 on 2020-10-10 06:36

from django.db import migrations, models
import toolbelt.utils


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20201002_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to=toolbelt.utils.banner_path),
        ),
    ]
