# Generated by Django 3.0.8 on 2020-08-13 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
        ('siteuser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinformation',
            name='interests',
            field=models.ManyToManyField(to='blog.Category'),
        ),
        migrations.AddField(
            model_name='siteuser',
            name='interests',
            field=models.ManyToManyField(to='blog.Category'),
        ),
        migrations.AddField(
            model_name='siteuser',
            name='roles',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Role'),
        ),
    ]
