# Generated by Django 3.0.8 on 2020-08-18 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteuser', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteuser',
            name='roles',
        ),
    ]
