# Generated by Django 3.1.2 on 2020-11-01 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteuser', '0002_auto_20201101_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinformation',
            name='picture',
            field=models.ImageField(upload_to=''),
        ),
    ]
