# Generated by Django 3.0.8 on 2020-08-13 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
        ('siteuser', '0002_auto_20200813_2334'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbookmarks',
            name='blog_post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.BlogPost'),
        ),
        migrations.AddField(
            model_name='userlikes',
            name='blog',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.BlogPost'),
        ),
    ]
