# Generated by Django 3.0.8 on 2020-08-18 03:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200818_0903'),
        ('siteuser', '0002_remove_siteuser_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteuser',
            name='roles',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Role'),
        ),
    ]
