# Generated by Django 3.1.2 on 2020-10-31 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteuser', '0002_auto_20201031_0126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteuser',
            name='roles',
        ),
    ]
