# Generated by Django 3.1.2 on 2020-10-29 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteuser', '0004_auto_20200823_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinformation',
            name='full_introduction',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='introduction',
            field=models.CharField(max_length=200),
        ),
    ]
