# Generated by Django 3.1.2 on 2020-11-01 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20201101_1631'),
        ('siteuser', '0004_remove_personalinformation_interests'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinformation',
            name='interests',
            field=models.ManyToManyField(to='blog.Category'),
        ),
    ]
