# Generated by Django 3.1.2 on 2020-11-01 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteuser', '0005_personalinformation_interests'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalinformation',
            name='interests',
        ),
        migrations.RemoveField(
            model_name='siteuser',
            name='interests',
        ),
        migrations.RemoveField(
            model_name='siteuser',
            name='roles',
        ),
        migrations.RemoveField(
            model_name='userbookmarks',
            name='blog_post',
        ),
        migrations.RemoveField(
            model_name='userlikes',
            name='blog',
        ),
    ]
