# Generated by Django 3.1.2 on 2020-11-01 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_role_role_name'),
        ('siteuser', '0006_auto_20201101_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinformation',
            name='interests',
            field=models.ManyToManyField(to='blog.Category'),
        ),
        migrations.AddField(
            model_name='siteuser',
            name='interests',
            field=models.ManyToManyField(to='blog.Category'),
        ),
        migrations.AddField(
            model_name='siteuser',
            name='roles',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.role'),
        ),
        migrations.AddField(
            model_name='userbookmarks',
            name='blog_post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.blogpost'),
        ),
        migrations.AddField(
            model_name='userlikes',
            name='blog',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.blogpost'),
            preserve_default=False,
        ),
    ]
