# Generated by Django 3.1.2 on 2021-01-14 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_notifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
